### ISSUE TITLE
Can this module purge/remove unwanted/unmanaged repos?

### ISSUE THREAD

**Issue by salderma** [voxpupuli/puppet-yum#104] opened 2018-06-19 16:15 UTC
Hi

As the subject implies, I'm looking for a way to ensure that puppet manages all the yum repos on a system.  I like that this module provides a group install feature, but it seems like it does not have the option to purge unmanaged repos.  Is that correct?

Thanks!

**Comment by SimonHoenscheid** [comment] 2018-08-27 16:18
Same question here

**Comment by ekohl** [comment] 2018-08-28 11:08
I think this just uses the `yumrepo` resource so the following will probably work:
```puppet
resources { 'yumrepo':
  purge => true,
}

**Comment by TJM** [comment] 2019-04-05 14:18
See #94

**Comment by ThoTischner** [comment] 2020-01-28 11:20
#94 Updated with workaround for the mean time.

**Comment by kenyon** [comment] 2022-12-06 23:37
Duplicate of #94.

**Closed by kenyon** 2022-12-06 23:37 UTC
Labels: duplicate, question
