### ISSUE TITLE
--knock-out-prefix "--" knocks out valid content of yum::gpgkeys 

### ISSUE THREAD

**Issue by alexskr** [voxpupuli/puppet-yum#111] opened 2018-08-07 21:25 UTC
Most of the yum gpg keys start with something like '-----BEGIN PGP PUBLIC KEY BLOCK-----'
which gets knocked out by --knock-out-prefix "--" when hiera deep merges yum::gpgkeys set outside of the module.   

This module works fine when I change --knock-out-prefix to a different value.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10
- Ruby:
- Distribution:  EL7
- Module version: 3.1

## How to reproduce (e.g Puppet code you use)

add yum::gpgkey with defined content outside of module bundled hiera.

## What are you seeing
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Missing params: $content or $source must be specified at /etc/puppetlabs/code/environments/production/modules/yum/manifests/gpgkey.pp:49:18

**Comment by pdemonaco** [comment] 2018-08-23 15:25
I can confirm that this issue also applies to puppet 5.5.

Is the inclusion of a knockout prefix actually even relevant for yum::gpgkeys? I would suggest removing it as I'm having a hard time imagining where this would come in handy given the structure of the module.

**Comment by avidspartan1** [comment] 2018-10-05 12:42
I've addressed this issue in [my PR](https://github.com/voxpupuli/puppet-yum/pull/121). I don't see why a knockout prefix is necessary, especially for GPG keys--so I removed it.

**Comment by dhoppe** [comment] 2019-04-05 11:40
I think this issue can be closed, since the pull request #121 was merged.

**Closed by dhoppe** 2019-04-05 11:40 UTC
