### ISSUE TITLE
In Puppet 6, remove_undef_values doesn't work as expected

### ISSUE THREAD

**Issue by avidspartan1** [voxpupuli/puppet-yum#120] opened 2018-10-01 17:06 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.0.0
- Ruby: 2.0.0p648
- Distribution: RHEL 7
- Module version: 3.1.0

## How to reproduce (e.g Puppet code you use)

1. Include the module in Puppet 6, any way you'd like.

## What are you seeing

The puppet run fails due to trying to get the "length" member from a Nil object (because remove_undef_values does not remove the undef (Nil) value).

## What behaviour did you expect instead

Puppet runs without errors.

## Output log
Server Error: Evaluation Error: Error while evaluating a Function Call, undefined method 'length' for nil:NilClass (file: /etc/puppetlabs/code/environments/production/modules/yum/manifests/init.pp, line: 222, column: 20) on node mynode.com.

## Any additional information you'd like to impart
I'm submitting a PR to fix this issue by removing undefined values with a filter.

**Comment by cbb-colab** [comment] 2018-10-04 09:46
I guess my (unexpected behaviour is similar, on my agent (RHEL7) I got:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, undefined method `length' for nil:NilClass (file: /etc/puppetlabs/code/environments/production/modules/yum/manifests/init.pp, line: 222, column: 20) on node template.test.intern

on the "puppet agent -t" command

Root cause was on the puppet master I upgraded from puppet 5.5 to 6.0 (already installed "puppet module install puppet-yum --version 3.1.0" as of puppet 5.5)

In my site.pp I have the offending line/class

class { 'yum': manage_os_default_repos => true, }

which I now have to comment to let my puppet agent not to fail

Please fix, maybe the root cause is as written above

**Comment by avidspartan1** [comment] 2018-10-04 13:45
Take a look at [my commit](https://github.com/voxpupuli/puppet-yum/pull/121/commits/d80cfc871a7b8e05aa1e5893a6d5edce9ee40415) to see my fix to what the underlying problem is. The problem is that puppet's "remove_undef_values" method does not work as expected and even states in the ruby file that it is not the "best practice" way of removing undefined values.

**Comment by dhoppe** [comment] 2019-04-05 11:38
I think this issue can be closed, since the pull request #121 was merged.

**Closed** 2019-04-05 11:38 UTC
